# Generated by Django 4.2.10 on 2024-04-18 03:42

from django.db import migrations

from manual.operations.manual_operations import ManualOperation


def _one_off_allele_liftover(apps, _schema_editor):
    AlleleLiftover = apps.get_model("snpdb", "AlleleLiftover")

    records = []
    for al in AlleleLiftover.objects.filter(error_message__isnull=False):
        al.error = {"message": al.error_message}
        records.append(al)

    PROCESSING_STATUS_ERROR = 'E'

    AlleleLiftover.objects.bulk_update(records, fields=["error"], batch_size=1024)
    # Any existing ones were once error, so set to be error
    AlleleLiftover.objects.all().update(status=PROCESSING_STATUS_ERROR)


def _has_allele_and_liftover(apps):
    Allele = apps.get_model("snpdb", "Allele")
    LiftoverRun = apps.get_model("snpdb", "LiftoverRun")
    return Allele.objects.exists() and LiftoverRun.objects.exists()


class Migration(migrations.Migration):
    """ AlleleLiftover (formerly LiftoverError) - move text field to JSON """
    dependencies = [
        ("snpdb", "0129_rename_error_variantallele_clingen_error_and_more"),
    ]

    operations = [
        migrations.RunPython(_one_off_allele_liftover),
        ManualOperation(task_id=ManualOperation.task_id_manage(["one_off_legacy_populate_allele_liftover"]),
                        test=_has_allele_and_liftover),

    ]
